### PR TITLE
Update Urls branch 2.2

### PR DESCRIPTION
**Pull request by yugeshk**
Updates the urls in Readme and Man page similar to other branches.

### CODE REVIEW

**Comment by dashohoxha** [comment]
It looks ok. You have forgotten to replace gnupg-2.1 with gnupg-2.2 on README (at Installation, `git clone ...`. Fix this one as well and I will accept the PR.

By the way, what editor are you using? Does it have a **Find/Replace in All Files** feature?

**Comment by yugeshk** [comment]
Done. Sorry for the delays. University end semester exams are on. :sweat_smile: 

Also, I use vim. I'm pretty sure there is a way to replace in All Files (since technically, vim can do everything) - but I'm not really sure how. I just did a replace all in individual files.

**Review by dashohoxha — APPROVED** [review]
It looks ok.

**Comment by dashohoxha** [comment]
> Also, I use vim. I'm pretty sure there is a way to replace in All Files (since technically, vim can do everything) - but I'm not really sure how.

I use vim too, and I am sure it is a powerful editor and can do almost everything. But I use it mostly as a sysadmin (for configuration files etc.) For software development I prefer Emacs. I would suggest everybody to give it a try some time (when you can find some free time for learning new things). It seems a bit difficult in the beginning, but later it pays off.

You can start from this guide: https://github.com/redguardtoo/mastering-emacs-in-one-year-guide/blob/master/guide-en.org

**Comment by dashohoxha** [comment]
@yugeshk I see that you have cloned the repository first, and then you made a PR. Nothing wrong with this, but you can also create a new branch in order to make a PR.
For more details see this (if you have missed it): https://github.com/orgs/EasyGnuPG/teams/egpg/discussions/2

**Pull request merged**
